const items = [
  {
    name: "Samsung Galaxy S23",
    category: "Smartphones",
    quantity: 50,
    price: 799,
    description: "Latest Samsung Galaxy S23 with 5G support.",
  },
  {
    name: "Apple iPhone 14 Pro",
    category: "Smartphones",
    quantity: 30,
    price: 999,
    description: "Apple iPhone 14 Pro with A16 Bionic chip.",
  },
  {
    name: "Dell XPS 15",
    category: "Laptops",
    quantity: 20,
    price: 1299,
    description: "Dell XPS 15 with 16GB RAM and 512GB SSD.",
  },
  {
    name: "HP Spectre x360",
    category: "Laptops",
    quantity: 15,
    price: 1199,
    description: "HP Spectre x360 with 14-inch display.",
  },
  {
    name: "Sony WH-1000XM4",
    category: "Headphones",
    quantity: 40,
    price: 349,
    description: "Sony WH-1000XM4 noise-canceling headphones.",
  },
  {
    name: "Bose QuietComfort 35 II",
    category: "Headphones",
    quantity: 25,
    price: 299,
    description: "Bose QuietComfort 35 II with wireless connectivity.",
  },
  {
    name: "LG 55UN7000PUA",
    category: "Televisions",
    quantity: 10,
    price: 799,
    description: "55-inch LG Smart TV with 4K resolution.",
  },
  {
    name: "Samsung QN55Q70RAFXZA",
    category: "Televisions",
    quantity: 5,
    price: 999,
    description: "Samsung QN55Q70RAFXZA with Quantum Dot technology.",
  },
  {
    name: "Canon EOS R5",
    category: "Cameras",
    quantity: 8,
    price: 3899,
    description: "Canon EOS R5 mirrorless camera.",
  },
  {
    name: "Sony Alpha 7 IV",
    category: "Cameras",
    quantity: 6,
    price: 2499,
    description: "Sony Alpha 7 IV with 33MP sensor.",
  },
  {
    name: "Bose SoundLink Revolve",
    category: "Speakers",
    quantity: 12,
    price: 199,
    description: "Portable Bose SoundLink Revolve speaker.",
  },
  {
    name: "JBL Flip 5",
    category: "Speakers",
    quantity: 18,
    price: 149,
    description: "JBL Flip 5 waterproof Bluetooth speaker.",
  },
  {
    name: "Logitech G502 HERO",
    category: "Gaming Accessories",
    quantity: 22,
    price: 49,
    description: "Logitech G502 HERO gaming mouse.",
  },
  {
    name: "Razer DeathAdder V2",
    category: "Gaming Accessories",
    quantity: 15,
    price: 59,
    description: "Razer DeathAdder V2 gaming mouse.",
  },
  {
    name: "Asus ROG Swift PG279QM",
    category: "Monitors",
    quantity: 7,
    price: 499,
    description: "Asus ROG Swift PG279QM gaming monitor.",
  },
  {
    name: "Dell UltraSharp U2720Q",
    category: "Monitors",
    quantity: 5,
    price: 699,
    description: "Dell UltraSharp U2720Q 4K monitor.",
  },
  {
    name: "Anker PowerCore 26800 PD",
    category: "Power Banks",
    quantity: 25,
    price: 59,
    description: "Anker PowerCore 26800 PD portable charger.",
  },
  {
    name: "Aukey 20000mAh Power Bank",
    category: "Power Banks",
    quantity: 30,
    price: 39,
    description: "Aukey 20000mAh power bank with multiple USB ports.",
  },
  {
    name: "Samsung 970 EVO Plus NVMe M.2 1TB",
    category: "Storage",
    quantity: 10,
    price: 149,
    description: "Samsung 970 EVO Plus NVMe M.2 1TB SSD.",
  },
  {
    name: "Crucial P5 Plus NVMe M.2 1TB",
    category: "Storage",
    quantity: 8,
    price: 129,
    description: "Crucial P5 Plus NVMe M.2 1TB SSD.",
  },
]

module.exports = items
